UWP V8 job + relwithdebuginfo (#62)
- new UWP/V8 job
- fix `Error C2039: 'TerminateThread': is not a member of 'global
namespace'`
- build as RelWithDebInfo instead of Debug
- hide ` Warning C4996:
'std::codecvt_utf8_utf16<char16_t,1114111,(std::codecvt_mode)0>':
warning STL4017`